avoid NPE:
java.lang.NullPointerException: Cannot invoke "org.sejda.sambox.cos.COSString.getString()" because the return value of "org.sejda.sambox.pdmodel.interactive.form.DefaultAppearanceHelper.getDefaultAppearance(org.sejda.sambox.pdmodel.interactive.form.PDField)" is null
	at org.sejda.sambox.pdmodel.interactive.form.PDVariableText.getDefaultAppearance(PDVariableText.java:83)