Bugfix: We came across a document where form flattening would fail due to carriage return
java.lang.IllegalArgumentException: U+000D is not available in this font's encoding: MacRomanEncoding with differences
	at org.sejda.sambox.pdmodel.font.PDTrueTypeFont.encode(PDTrueTypeFont.java:332)
	at org.sejda.sambox.pdmodel.font.PDFont.encode(PDFont.java:286)
	at org.sejda.sambox.pdmodel.font.PDFont.getStringWidth(PDFont.java:316)
	at org.sejda.sambox.pdmodel.interactive.form.PlainText$Paragraph.getLines(PlainText.java:172)
	at org.sejda.sambox.pdmodel.interactive.form.PlainTextFormatter.format(PlainTextFormatter.java:179)
	at org.sejda.sambox.pdmodel.interactive.form.AppearanceGeneratorHelper.insertGeneratedAppearance(AppearanceGeneratorHelper.java:395)
	at org.sejda.sambox.pdmodel.interactive.form.AppearanceGeneratorHelper.setAppearanceContent(AppearanceGeneratorHelper.java:267)
	at org.sejda.sambox.pdmodel.interactive.form.AppearanceGeneratorHelper.setAppearanceValue(AppearanceGeneratorHelper.java:162)
	at org.sejda.sambox.pdmodel.interactive.form.PDTextField.constructAppearances(PDTextField.java:264)
	at org.sejda.sambox.pdmodel.interactive.form.PDAcroForm.refreshAppearances(PDAcroForm.java:266)
	at org.sejda.sambox.pdmodel.interactive.form.PDAcroForm.flatten(PDAcroForm.java:161)