Bugfix: leniently handle missing /DA entries
java.lang.IllegalArgumentException: /DA is a required entry
	at org.sejda.sambox.pdmodel.interactive.form.PDDefaultAppearanceString.(PDDefaultAppearanceString.java:87)
	at org.sejda.sambox.pdmodel.interactive.form.PDVariableText.getDefaultAppearanceString(PDVariableText.java:96)
	at org.sejda.sambox.pdmodel.interactive.form.PDVariableText.getAppearanceFont(PDVariableText.java:245)