Fix crash due to nested endText() calls when generating form field appearance.
java.lang.IllegalStateException: Error: You must call beginText() before calling endText.
	at org.sejda.sambox.pdmodel.PDPageContentStream.endText(PDPageContentStream.java:291)
	at org.sejda.sambox.pdmodel.interactive.form.AppearanceGeneratorHelper.insertGeneratedAppearance(AppearanceGeneratorHelper.java:507)
	at org.sejda.sambox.pdmodel.interactive.form.AppearanceGeneratorHelper.setAppearanceContent(AppearanceGeneratorHelper.java:360)
	at org.sejda.sambox.pdmodel.interactive.form.AppearanceGeneratorHelper.setAppearanceValue(AppearanceGeneratorHelper.java:232)
	at org.sejda.sambox.pdmodel.interactive.form.PDListBox.constructAppearances(PDListBox.java:85)
	at org.sejda.sambox.pdmodel.interactive.form.PDTerminalField.applyChange(PDTerminalField.java:175)
	at org.sejda.sambox.pdmodel.interactive.form.PDChoice.setValue(PDChoice.java:380)