Avoid PDFunction.create NPE: Cannot invoke "org.sejda.sambox.cos.COSBase.getCOSObject()" because "function" is null
java.lang.NullPointerException: Cannot invoke "org.sejda.sambox.cos.COSBase.getCOSObject()" because "function" is null
	at org.sejda.sambox.pdmodel.common.function.PDFunction.create(PDFunction.java:114)
	at org.sejda.sambox.pdmodel.graphics.color.PDSeparation.<init>(PDSeparation.java:89)
	at org.sejda.sambox.pdmodel.graphics.color.PDColorSpace.createUncached(PDColorSpace.java:231)
	at org.sejda.sambox.pdmodel.graphics.color.PDColorSpace.create(PDColorSpace.java:96)
	at org.sejda.sambox.pdmodel.PDResources.getColorSpace(PDResources.java:226)
	at org.sejda.sambox.pdmodel.PDResources.getColorSpace(PDResources.java:196)
	at org.sejda.sambox.contentstream.operator.color.SetNonStrokingColorSpace.process(SetNonStrokingColorSpace.java:57)
	at org.sejda.sambox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:896)