Bugfix: allow checking PDCheckbox which has no on values defined.
java.lang.IllegalArgumentException: value '' is not a valid option for the field redacted, valid values are: [] and Off
	at org.sejda.sambox.pdmodel.interactive.form.PDButton.checkValue(PDButton.java:343) ~[sambox-1.0.52.RELEASE.jar:na]
	at org.sejda.sambox.pdmodel.interactive.form.PDButton.setValue(PDButton.java:147) ~[sambox-1.0.52.RELEASE.jar:na]
	at org.sejda.sambox.pdmodel.interactive.form.PDCheckBox.check(PDCheckBox.java:76) ~[sambox-1.0.52.RELEASE.jar:na]