closed #162 NPE parsing colorSpace
java.lang.NullPointerException: Cannot invoke "org.sejda.sambox.cos.COSBase.getCOSObject()" because "colorSpace" is null
	at org.sejda.sambox.pdmodel.graphics.color.PDColorSpace.createUncached(PDColorSpace.java:137)
	at org.sejda.sambox.pdmodel.graphics.color.PDColorSpace.createUncached(PDColorSpace.java:257)
	at org.sejda.sambox.pdmodel.graphics.color.PDColorSpace.create(PDColorSpace.java:96)
	at org.sejda.sambox.pdmodel.graphics.color.PDColorSpace.create(PDColorSpace.java:76)
	at org.sejda.sambox.pdmodel.graphics.image.PDImageXObject.getColorSpace(PDImageXObject.java:629)
	at org.sejda.sambox.pdmodel.graphics.image.SampledImageReader.getRGBImage(SampledImageReader.java:152)
	at org.sejda.sambox.pdmodel.graphics.image.PDImageXObject.getImage(PDImageXObject.java:299)
	at org.sejda.sambox.rendering.PageDrawer.drawImage(PageDrawer.java:1069)
	at org.sejda.sambox.contentstream.operator.graphics.DrawObject.process(DrawObject.java:65)
	at org.sejda.sambox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:896)
	at org.sejda.sambox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:542)
	at org.sejda.sambox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:520)
	at org.sejda.sambox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:161)
	at org.sejda.sambox.rendering.PageDrawer.drawPage(PageDrawer.java:263)
	at org.sejda.sambox.rendering.PDFRenderer.renderImage(PDFRenderer.java:315)
	at org.sejda.sambox.rendering.PDFRenderer.renderImage(PDFRenderer.java:233)
	at org.sejda.sambox.rendering.PDFRenderer.renderImageWithDPI(PDFRenderer.java:218)