Avoid crashing when field widget has invalid default appearance string, use a fallback value instead:
java.io.IOException: Missing operands for set font operator [12]
	at org.sejda.sambox.pdmodel.interactive.form.PDDefaultAppearanceString.processSetFont(PDDefaultAppearanceString.java:170)
	at org.sejda.sambox.pdmodel.interactive.form.PDDefaultAppearanceString.processOperator(PDDefaultAppearanceString.java:143)
	at org.sejda.sambox.pdmodel.interactive.form.PDDefaultAppearanceString.processAppearanceStringOperators(PDDefaultAppearanceString.java:119)
	at org.sejda.sambox.pdmodel.interactive.form.PDDefaultAppearanceString.(PDDefaultAppearanceString.java:92)
	at org.sejda.sambox.pdmodel.interactive.form.AppearanceGeneratorHelper.getWidgetDefaultAppearanceString(AppearanceGeneratorHelper.java:269)
	at org.sejda.sambox.pdmodel.interactive.form.AppearanceGeneratorHelper.setAppearanceValue(AppearanceGeneratorHelper.java:190)
	at org.sejda.sambox.pdmodel.interactive.form.PDTextField.constructAppearances(PDTextField.java:264)
	at org.sejda.sambox.pdmodel.interactive.form.PDTerminalField.applyChange(PDTerminalField.java:172)
	at org.sejda.sambox.pdmodel.interactive.form.PDTextField.setValue(PDTextField.java:219)